### ISSUE TITLE
Labels not right justified

### ISSUE THREAD

**Issue by mitch-besser** [ElectronicControlsDesign/LoginDialog#4]
The labels (Username and Password) must be right justified, not left justified.

**Comment by dbaltimore** [comment]
I did add this code to the labels, but it moved the text far to the left. Not sure why yet
Still working on it.
horizontalAlignment: Text.AlignRight

**Comment by mitch-besser** [comment]
@dbaltimore not seeing your changes on github. I'm not seeing any code changes from you at all. Either I'm missing something or you are not pushing. Can you verify your push is working?

**Comment by dbaltimore** [comment]
Re: [ElectronicControlsDesign/LoginDialog] Labels not right justified (#4)


I am working in Joseph's branch as I was seeing no changes in the Master branch/


-- 
Best regards,
 David                            mailto:dbaltimore@BaltimoreLabs.com



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by JosephAlfonso** [comment]
@dbaltimore: Please work on the master branch. 

I have added `horizontalAlignment: Text.AlignRight` and it works. However, when we do translate the labels via the Test Translate button. This happens...

![capture](https://cloud.githubusercontent.com/assets/3060074/21554172/297db24c-cdc2-11e6-9b0a-cfef140253ad.PNG)

**Comment by dbaltimore** [comment]
When I started using your repo, I saw empty framework code but Joseph had your current code. 

I'll recheck the master and get the code.

I had the danger problem with right justifying the labels. It may be an interaction in the grid. Containers in qml tread to have a mind of their own. I'm researching it.

On December 29, 2016 3:27:48 PM EST, JosephAlfonso <notifications@github.com> wrote:
>@dbaltimore: Please work on the master branch. 
>
>I have added `horizontalAlignment: Text.AlignRight` and it works.
>However, when we do translate the labels via the Test Translate button.
>This happens...
>
>![capture](https://cloud.githubusercontent.com/assets/3060074/21554172/297db24c-cdc2-11e6-9b0a-cfef140253ad.PNG)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ElectronicControlsDesign/LoginDialog/issues/4#issuecomment-269688545

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JosephAlfonso** [comment]
Great job!
